development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: diarrhea_development
  pool: 50
  username: root
#  password: jybrctu
  socket: /var/run/mysqld/mysqld1.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: diarrhea_test
  pool: 5
  username: root
  password: jybrctu
#  socket: /var/run/mysqld/mysqld1.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: diarrhea_production
  pool: 50
  username: root
  password:
#  socket: /var/run/mysqld/mysqld.sock
